import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'
import { calculateRequiredPaperQuantity } from '../src/features/job-cards/jobCardCalculations.ts'

test('Required Item Qty applies wastage and flute draw ratio', () => {
  assert.equal(calculateRequiredPaperQuantity(495, 1780, 230, 500), 106.392825)
  assert.equal(calculateRequiredPaperQuantity(495, 1780, 120, 500, 'B'), 75.492648)
  assert.equal(calculateRequiredPaperQuantity(0, 1780, 120, 500, 'B'), null)
})

test('Job Cards are created additively from Production Planned lines', async () => {
  const [migration, api, component, styles, dashboard] = await Promise.all([
    readFile('migrations/0028_create_job_cards.sql', 'utf8'),
    readFile('functions/api/job-cards.ts', 'utf8'),
    readFile('src/features/job-cards/JobCards.tsx', 'utf8'),
    readFile('src/features/job-cards/job-cards.css', 'utf8'),
    readFile('src/Dashboard.tsx', 'utf8'),
  ])
  assert.match(migration, /CREATE TABLE IF NOT EXISTS job_cards/)
  assert.match(migration, /production_plan_line_id INTEGER NOT NULL UNIQUE/)
  assert.doesNotMatch(migration, /\b(?:DELETE|DROP|TRUNCATE|REPLACE)\b/i)
  assert.match(api, /menu_key = 'job-cards'/)
  assert.match(api, /INSERT OR IGNORE INTO job_cards/)
  assert.match(api, /plan\.status <> 'DRAFT'/)
  assert.match(api, /LEFT JOIN product_specification_records/)
  assert.match(api, /spec\.product_name/)
  assert.match(api, /'JC-' \|\| printf\('%06d', line\.id\)/)
  assert.match(component, /Ready to Create/)
  assert.match(component, /production-planned-toolbar job-cards-toolbar/)
  assert.match(component, /aria-label="Job Card view"/)
  assert.match(component, /aria-label="Clear filters"/)
  assert.match(component, /className="job-cards-groups"/)
  assert.match(component, /className="job-grid-select"/)
  assert.match(component, /className="job-grid-product-name"/)
  assert.match(component, /className="job-grid-product-description"/)
  assert.match(component, /className="job-card-specification-link"/)
  assert.match(component, /setViewingSpecification\(line\)/)
  assert.match(component, /role="dialog" aria-modal="true" aria-labelledby="job-card-specification-title"/)
  assert.match(component, /Paper Composition/)
  assert.match(component, /Production Stages/)
  assert.match(component, /<dt>Board \/ Creasing Allowance<\/dt><dd>\{attributes\.board_creasing_allowance \|\| ''\}<\/dd>/)
  assert.match(component, /className="group-product" colSpan=\{2\}/)
  assert.match(component, /<th>Product Name<\/th><th>Product Description<\/th>/)
  assert.match(component, /className="numeric job-cards-box-qty"/)
  assert.match(component, /calculateRequiredPaperQuantity\(deckle, rotary, layer\.gsm, line\.production_quantity, layer\.flute\)/)
  assert.match(component, /calculateRotarySize\(Number\(line\.width_mm\), Number\(line\.height_mm\), creasingAllowance\)/)
  assert.match(component, /calculateSlottingSize\(Number\(line\.width_mm\), creasingAllowance\)/)
  assert.doesNotMatch(component, /\(2 \* line\.length_mm\) \+ \(2 \* line\.width_mm\) \+ 50/)
  assert.match(component, /<th>Qty \(Kg\)<\/th>/)
  assert.match(component, /numberText\(boxWeight \/ 1000\)/)
  assert.equal(component.match(/Box Wt\. \(Kg\)/g)?.length, 2)
  assert.match(component, /<th className="job-card-required-qty-label" rowSpan=\{3\}>Req\. Qty \(Kg\)<\/th><td className="job-card-required-qty-value" rowSpan=\{3\}><\/td>/)
  assert.match(component, /<th>Metpad \(Size\)<\/th><td><\/td>/)
  assert.match(component, /<th>Window \(Size\)<\/th><td><\/td>/)
  assert.match(component, /Order &amp; Item/)
  assert.match(component, /className=\{selected\.includes\(line\.production_plan_line_id\) \? 'is-selected' : ''\}/)
  assert.match(component, /Create Job Cards/)
  assert.match(component, /className="job-cards-primary job-cards-print"[^>]*>[\s\S]*?Print Selected/)
  assert.match(component, /document\.title = selectedLines\.length/)
  assert.match(component, /window\.addEventListener\('afterprint'/)
  assert.match(component, /Job Card: \{line\.job_number\}/)
  assert.match(component, /className="job-card-logo" src="\/assets\/PC-Bord-Logo-only-transparent\.png" alt="Polarcanvas"/)
  assert.match(component, /job-card-label-column/)
  assert.match(component, /job-card-col-process/)
  for (const heading of ['PRODUCTION JOB CARD', 'REQUIRED ITEM', 'PROCESS', 'Start Datetime', 'End Datetime', 'Reel No.', 'In Reel Weight', 'Out Reel Weight', 'Remaining Reel Weight', 'Out Qty', 'Emp. Name', 'Supervisor', 'Quality', 'Dispatch', 'Manufactured Qty']) {
    assert.match(component, new RegExp(heading))
  }
  assert.doesNotMatch(component, /<th>(?:Start|End) Time<\/th>/)
  assert.match(component, /Size \(MM\)/)
  assert.match(component, /Req\. Size \(CM\)/)
  assert.match(component, /numberText\(deckle \/ 10\)/)
  assert.match(component, /numberText\(rotary \/ 10\).*cm/)
  assert.doesNotMatch(component, /rotary \/ 25\.4/)
  assert.match(component, /const sizeCm = .*Number\(value\) \/ 10/)
  assert.match(component, /\$\{size\} mm \| \$\{sizeCm\} cm/)
  assert.doesNotMatch(component, /Size \(Inch\)/)
  assert.match(component, /className="job-cards-product">\{line\.product_name\}<\/td>/)
  assert.match(component, /className="job-cards-product">\{line\.item_description \|\| line\.item_name\}<\/td>/)
  assert.match(component, /<th>PC Item Code<\/th><td>\{line\.specification_code\}<\/td>/)
  assert.match(component, /<th>Product Spec<\/th><td colSpan=\{3\}>\{line\.item_description \|\| line\.item_name\}<\/td>/)
  assert.match(component, /<th>Joint<\/th><td colSpan=\{3\}>\{attributes\.joint_type \|\| ''\}<\/td>/)
  assert.match(component, /className="job-card-creasing-summary"/)
  for (const field of ['Slotting Size', 'Board / Creasing Allowance', 'Adjusted Width', 'Top Flap', 'Box Height', 'Bottom Flap']) assert.match(component, new RegExp(`<dt>${field.replace('/', '\\/')}<\\/dt>`))
  assert.match(component, /className=\{stage === 'Corrugation' \? 'job-card-corrugation-row' : ''\}/)
  assert.match(component, /stage === 'Board \/ Sheet Cutting' \? <>Board \/ Sheet<br \/>Cutting<\/>/)
  assert.match(component, /stage === 'Quality Inspection' \? <>Quality<br \/>Inspection<\/>/)
  assert.match(component, /stage === 'Bundling \/ Packing' \? <>Bundling \/<br \/>Packing<\/>/)
  assert.match(component, /function ReelDetailCell/)
  assert.match(component, /stage !== 'Paper Cutting' && stage !== 'Corrugation'/)
  assert.match(component, /field="reel_number" secondField="reel_number_2"/)
  assert.match(component, /field="in_reel_weight" secondField="in_reel_weight_2" numeric/)
  assert.match(component, /field="out_reel_weight" secondField="out_reel_weight_2" numeric/)
  assert.match(component, /field="remaining_reel_weight" secondField="remaining_reel_weight_2" numeric/)
  assert.match(component, /<th>Sales Order<\/th><td>\{line\.sales_order_number\}<\/td>/)
  assert.doesNotMatch(component, /<th>Order No\.<\/th>/)
  assert.doesNotMatch(component, /<th>Article (?:No\.|Name)<\/th>/)
  assert.match(styles, /size:\s*A4 portrait/)
  assert.match(styles, /@page \{[^}]*margin:\s*0/s)
  assert.match(styles, /width:\s*210mm/)
  assert.match(styles, /height:\s*297mm/)
  assert.match(styles, /padding:\s*10mm/)
  assert.match(styles, /font-size:\s*7\.5pt/)
  assert.match(styles, /print-color-adjust:\s*exact/)
  assert.match(styles, /grid-template-columns:\s*repeat\(5, 1fr\)/)
  assert.equal(component.match(/className="job-card-heading"/g)?.length, 3)
  assert.match(styles, /\.job-card-sheet \.job-card-heading \{[^}]*font:\s*800 13pt\/1\.1 Arial[^}]*!important/s)
  assert.match(styles, /\.job-card-sheet h1 \{[^}]*text-align:\s*center/s)
  assert.match(styles, /\.job-card-sheet header strong \{[^}]*position:\s*absolute/s)
  assert.match(styles, /\.job-card-logo \{[^}]*left:\s*2mm[^}]*width:\s*9mm/s)
  assert.match(styles, /job-cards-groups \.group-production/)
  assert.match(styles, /\.job-card-specification-link \{/)
  assert.match(styles, /\.job-card-specification-backdrop \{ position:fixed;/)
  assert.match(styles, /button\.job-cards-print \{ border-color:#1d4ed8; background:#2563eb; \}/)
  assert.match(styles, /overflow-x:\s*hidden/)
  assert.match(styles, /\.job-cards-list table \{[^}]*min-width:\s*0/s)
  assert.match(styles, /\.job-cards-list th:last-child,\.job-cards-list \.job-cards-box-qty \{ text-align:center; \}/)
  assert.match(styles, /\.job-card-split-reels span \{[^}]*height:\s*50%/s)
  assert.match(styles, /td\.job-card-split-reels::after,\.job-card-process td\.job-card-split-process-values::after \{[^}]*top:\s*50%;[^}]*border-top:/s)
  assert.match(styles, /\.job-card-process \.job-card-corrugation-row td \{ height:\s*13mm; \}/)
  assert.match(styles, /\.job-card-process td\.job-card-process-name \{[^}]*white-space:\s*normal;[^}]*overflow-wrap:\s*anywhere;/s)
  assert.match(styles, /\.job-card-creasing-summary \{ display: grid; grid-template-columns: repeat\(6,minmax\(0,1fr\)\);/)
  assert.match(styles, /break-after:\s*page/)
  assert.match(dashboard, /<JobCards \/>/)
  const placeholderKeys = dashboard.match(/const NEW_MODULE_MENU_KEYS = new Set\(\[([\s\S]*?)\]\)/)?.[1] ?? ''
  assert.doesNotMatch(placeholderKeys, /'job-cards'|'job-tracking'/)
  const panelHeadingKeys = dashboard.match(/const PANEL_HEADING_MENU_KEYS = new Set\(\[([\s\S]*?)\]\)/)?.[1] ?? ''
  assert.doesNotMatch(panelHeadingKeys, /'job-cards'/)
  const documentPageClass = dashboard.match(/<div className=\{`dashboard-card([\s\S]*?)document-form-page/)?.[1] ?? ''
  assert.match(documentPageClass, /selectedItem\.key === 'job-cards'/)
  assert.match(documentPageClass, /selectedItem\.key === 'job-tracking'/)
})
