import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

test('product specifications use cached customers and cached Zoho items', async () => {
  const [component, itemsApi, itemsLibrary] = await Promise.all([
    readFile('src/features/product-specifications/ProductSpecifications.tsx', 'utf8'),
    readFile('functions/api/items.ts', 'utf8'),
    readFile('lib/items.ts', 'utf8'),
  ])
  assert.match(component, /getCustomers\(\)/)
  assert.match(component, /customer\.customer_name} - \$\{customer\.gst_number}/)
  assert.match(component, />\{customerDisplayName\(value\)}<\/option>/)
  assert.match(component, /getItems\(\)/)
  assert.match(component, /Promise\.allSettled/)
  assert.match(component, /specification\.customer_id === listCustomerId\)/)
  assert.doesNotMatch(component, /!listItemId \|\| specification\.item_id === listItemId/)
  assert.match(component, /response\.status === 401/)
  assert.match(component, /pc-tech-session-expired/)
  assert.match(component, /specificationsLoaded/)
  assert.match(component, /Unable to load saved specifications\. Refresh after checking the local backend\./)
  assert.match(itemsApi, /FROM item_cache/)
  assert.match(itemsApi, /isCurrentDailyCustomerCache/)
  assert.doesNotMatch(itemsApi, /paper_purchase_request_items|PC-TECH-FALLBACK/)
  assert.match(itemsApi, /ZohoBooks\.settings\.READ/)
  assert.match(itemsApi, /onRequestPost/)
  assert.match(itemsApi, /SUPERADMIN access required/)
  assert.match(itemsLibrary, /zohoGet\(`\/items/)
})

test('product specification persistence supports multiple variants and never deletes data', async () => {
  const [migration, variantMigration, codeMigration, productNameMigration, api] = await Promise.all([
    readFile('migrations/0016_create_item_cache_and_product_specifications.sql', 'utf8'),
    readFile('migrations/0018_create_product_specification_records.sql', 'utf8'),
    readFile('migrations/0019_add_polar_canvas_item_code.sql', 'utf8'),
    readFile('migrations/0027_add_optional_product_specification_product_name.sql', 'utf8'),
    readFile('functions/api/product-specifications.ts', 'utf8'),
  ])
  assert.match(migration, /CREATE TABLE IF NOT EXISTS item_cache/)
  assert.match(migration, /CREATE TABLE IF NOT EXISTS product_specifications/)
  assert.match(variantMigration, /CREATE TABLE IF NOT EXISTS product_specification_records/)
  assert.match(variantMigration, /INSERT OR IGNORE INTO product_specification_records/)
  assert.match(variantMigration, /FROM product_specifications/)
  assert.doesNotMatch(variantMigration, /UNIQUE\s*\(customer_id,\s*item_id\)/i)
  assert.doesNotMatch(api, /ON CONFLICT\(customer_id, item_id\)/)
  assert.match(codeMigration, /'PC-' \|\| printf\('%06d', id\)/)
  assert.match(codeMigration, /CREATE UNIQUE INDEX/)
  assert.match(productNameMigration, /ADD COLUMN product_name TEXT NOT NULL DEFAULT ''/)
  assert.doesNotMatch(`${migration}\n${variantMigration}\n${codeMigration}\n${productNameMigration}\n${api}`, /\b(?:DELETE|DROP|TRUNCATE|REPLACE)\b/i)
  assert.match(api, /WHERE customer_id = \?/)
  assert.match(api, /'so-specification-mapping'/)
})

test('product form supports item-aware dimensions, GSM, BF and print controls', async () => {
  const [component, styles, api] = await Promise.all([
    readFile('src/features/product-specifications/ProductSpecifications.tsx', 'utf8'),
    readFile('src/features/product-specifications/product-specifications.css', 'utf8'),
    readFile('functions/api/product-specifications.ts', 'utf8'),
  ])
  for (const field of ['length_mm', 'width_mm', 'height_mm', 'gsm', 'bf', 'print_required']) {
    assert.match(component, new RegExp(field))
  }
  for (const label of ['Customer', 'Item', 'Design Type']) {
    assert.match(component, new RegExp(`<span className="spec-field-label">${label} <b className="spec-required-mark"`))
  }
  assert.equal((component.match(/className="spec-required-mark"/g) ?? []).length, 3)
  assert.match(component, /<label>Product Name<input type="text" maxLength=\{200\} value=\{form\.product_name\}/)
  assert.doesNotMatch(component, /Product Name.*spec-required-mark/)
  assert.doesNotMatch(component, /Product Name<input[^>]*required/)
  assert.match(component, /product_name: specification\.product_name \|\| ''/)
  assert.match(api, /const productName = text\('product_name'\)\.slice\(0, 200\)/)
  assert.doesNotMatch(api, /Product Name are required/)
  assert.match(component, /detectType/)
  for (const ply of [2, 3, 5, 7, 9]) assert.match(component, new RegExp(`'${ply}'`))
  assert.match(component, /function matchingPlyItem\(items: Item\[\], currentItem: Item \| undefined, ply: string\)/)
  assert.match(component, /replace\(\/\\b\\d\+\\s\*ply\\b\/i, `\$\{ply\} Ply`\)/)
  assert.match(component, /const matchingItem = matchingPlyItem\(items, item, ply\)/)
  assert.match(component, /setItemId\(matchingItem\.item_id\)/)
  assert.match(component, /setListItemId\(matchingItem\.item_id\)/)
  assert.match(component, /Paper Composition/)
  assert.match(component, /attributes\.paper_layers\.length > 0 \? attributes\.paper_layers : buildPaperLayers\(savedPly, \[\]\)/)
  assert.match(component, /Select Ply above to enter paper composition\./)
  assert.match(component, /'Printing', 'Creasing',\s*'RS4', 'Slotting'/)
  assert.match(component, /Deckle Size/)
  assert.match(component, /type="text" value=\{layer\.deckle_size \|\| calculatedDeckle\(form\)\}/)
  assert.match(component, /updatePaperLayer\(index, 'deckle_size', e\.target\.value\)/)
  assert.match(component, /width \+ height \+ 20/)
  assert.match(component, /deckleMm \/ 10/)
  for (const calculatedField of ['Rotary Size', 'Sheet Size', 'Box Weight', 'Board GSM', '>BS<', 'Moisture']) {
    assert.match(component, new RegExp(calculatedField))
  }
  assert.match(component, /Lab test required/)
  assert.match(component, /sheetAreaSqM \* boardGsm \* 1\.05/)
  assert.match(component, /calculateRotarySize\(width, height, creasingAllowance\)/)
  assert.match(component, /calculateSlottingSize\(width, creasingAllowance\)/)
  assert.doesNotMatch(component, /rotaryMm = hasBoxDimensions \? \(2 \* length\) \+ \(2 \* width\) \+ 50/)
  assert.match(component, /deckleMm \/ 10.*rotaryMm \/ 10/)
  assert.match(component, /Sheet Size \(Deckle × Rotary\)/)
  assert.ok(component.indexOf('>Sheet Size (Deckle × Rotary)<input') < component.indexOf('>Slotting Size<input'))
  assert.match(component, /Slotting Size<input value=\{calculatedValues\.slottingSize\} readOnly/)
  assert.match(component, /Production Stages/)
  assert.match(component, /Board Type/)
  assert.match(component, /Plant Board/)
  assert.match(component, /Manual Board/)
  assert.match(api, /'board_type'/)
  assert.match(component, /Board \/ Creasing Allowance<select value=\{form\.board_creasing_allowance\}/)
  assert.match(component, /\['6', '7', '8', '10'\]\.map/)
  assert.ok(component.indexOf('>Print<select') < component.indexOf('>Board / Creasing Allowance<select'))
  assert.doesNotMatch(component, /Board \/ Creasing Allowance \(Result\)/)
  assert.match(api, /'board_creasing_allowance'/)
  assert.match(component, /<dt>Design Type<\/dt>.*<dt>Board Type<\/dt>/)
  assert.ok(component.indexOf('paper-composition') < component.indexOf('<strong>Production Stages<\/strong>'))
  assert.match(component, /defaultProductionStages/)
  for (const stage of ['Paper Cutting', 'Corrugation', 'Pasting', 'Board \/ Sheet Cutting', 'Printing', 'RS4', 'Creasing', 'Slotting', 'Die Cutting', 'Stitching \/ Gluing', 'Quality Inspection', 'Bundling \/ Packing']) {
    assert.match(component, new RegExp(stage))
  }
  assert.match(component, /Product Specification Report/)
  assert.match(component, /Box Dimension Drawing \(Isometric Projection\)/)
  assert.match(component, /product-spec-box-preview/)
  assert.match(component, /Generated from the Length, Width and Height above\./)
  assert.match(component, /IsometricBoxDrawing length=\{form\.length_mm\} width=\{form\.width_mm\} height=\{form\.height_mm\} creasingAllowance=\{form\.board_creasing_allowance\}/)
  assert.match(component, /SHEET SIZE/)
  assert.match(component, /DECKLE × ROTARY/)
  assert.match(component, /sheetDimension/)
  assert.match(component, /rotaryFormula/)
  assert.match(component, /deckleFormula/)
  assert.ok(component.indexOf('<h2>Production Stages</h2>') < component.indexOf('<h2>Box Dimension Drawing (Isometric Projection)</h2>'))
  assert.match(component, />PRODUCT SPECIFICATION<\/p>/)
  assert.match(component, /Polar Canvas Item Code : \{form\.polar_canvas_item_code\}/)
  assert.match(component, /Created DateTime/)
  assert.match(component, /Updated DateTime/)
  assert.match(component, /formatIstDateTime\(reportSpecification\?\.created_at\)/)
  assert.match(component, /formatIstDateTime\(reportSpecification\?\.updated_at\)/)
  assert.doesNotMatch(component, /Created \/ Updated DateTime/)
  assert.match(component, /Generated by PC-Tech \| Confidential \| Shred Upon Job Completion/)
  assert.doesNotMatch(component, /<dt>Item SKU<\/dt>/)
  assert.match(api, /attributes_json, created_at, updated_at/)
  assert.doesNotMatch(component, />PRODUCT SPECIFICATION REPORT<\/p>/)
  assert.match(component, /product-spec-report-a4/)
  assert.match(styles, /width:210mm/)
  assert.match(styles, /size:A4 portrait/)
  assert.match(styles, /\.spec-report-stages[^}]*font-size:11px/)
  assert.match(styles, /spec-report-details>div:nth-child\(9\).*nth-child\(10\).*grid-column:span 2/)
  assert.match(styles, /\.spec-report-details dd[^}]*white-space:nowrap/)
  assert.match(styles, /nth-child\(3\).*nth-child\(4\).*white-space:nowrap/)
  assert.match(component, /paper_layers/)
  assert.match(component, /Select joint/)
  assert.match(component, /Brass Pinning/)
  assert.match(component, /SS Pinning/)
  assert.match(component, /GI Pinning/)
  assert.match(component, /Select finish/)
  for (const heading of ['Layer Type', 'BF/RCT', 'Shade', 'Paper Grade', 'Flute']) assert.match(component, new RegExp(heading))
  for (const type of ['BOX', 'BOARD \/ SHEET', 'PAPER \/ ROLL', 'TAPE', 'FILM']) {
    assert.match(component, new RegExp(type))
  }
  assert.match(component, /Add Specification/)
  assert.match(component, /Polar Canvas Item Code/)
  assert.match(component, /readOnly/)
  assert.match(component, /padStart\(4, '0'\)/)
  assert.doesNotMatch(component, /Auto-generated on save/)
  assert.doesNotMatch(component, /Specification Exists/)
  assert.match(component, /Saved Specifications/)
  assert.match(component, /editingId === specification\.id \? 'is-current-specification'/)
  assert.match(styles, /tr\.is-current-specification/)
  assert.match(component, /specificationSize/)
  assert.match(component, /<th>#<\/th><th>PC Item Code<\/th><th>Product Name<\/th><th>Item<\/th><th>Size<\/th>/)
  assert.match(component, /Select a customer to display saved specifications/)
  assert.match(component, /All items/)
  assert.match(component, /'Locked' : 'Edit'/)
  assert.match(component, /> Clone</)
  assert.match(component, /editorRef\.current\?\.scrollIntoView\(\{ behavior: 'smooth', block: 'start' \}\)/)
  assert.doesNotMatch(component, /window\.scrollTo/)
  assert.match(component, /<th>Specification Notes<\/th>/)
  assert.match(component, /className="specification-notes"/)
  assert.doesNotMatch(component, /<th>GSM<\/th><th>BF<\/th><th>Print<\/th>/)
  assert.match(component, /colSpan=\{10\}/)
  assert.match(component, /const clone = \(specification: Specification\)/)
  assert.match(component, /formFromSpecification\(specification, nextItemCode\(\)\)/)
  assert.doesNotMatch(component, /No Zoho item description available/)
  assert.match(styles, /product-spec-technical \.product-spec-grid \{ grid-template-columns:repeat\(5,minmax\(0,1fr\)\)/)
  assert.match(styles, /input\[readonly\]/)
  assert.match(styles, /background:#edf9f1/)
  assert.match(styles, /spec-dimension-input::-webkit-inner-spin-button/)
})

test('planned Sales Order specifications are locked against edits with traceable context', async () => {
  const [component, api, styles] = await Promise.all([
    readFile('src/features/product-specifications/ProductSpecifications.tsx', 'utf8'),
    readFile('functions/api/product-specifications.ts', 'utf8'),
    readFile('src/features/product-specifications/product-specifications.css', 'utf8'),
  ])

  assert.match(api, /FROM production_plan_lines line/)
  assert.match(api, /line\.customer_product_specification_id = \?/)
  assert.match(api, /line\.approved_specification_revision_id = \?/)
  assert.match(api, /GROUP_CONCAT\(DISTINCT sales_order_number\)/)
  assert.match(api, /GROUP_CONCAT\(DISTINCT production_plan\)/)
  assert.match(api, /FROM so_line_child_specifications child/)
  assert.match(api, /This Product Specification cannot be edited because it is mapped to Sales Order/)
  assert.match(api, /}, 409\)/)
  assert.match(component, /locked_sales_orders/)
  assert.match(component, /specificationLockMessage/)
  assert.match(component, /Clone it to create a new specification\./)
  assert.match(component, /is-locked/)
  assert.match(component, /setReadOnlyMode\(Boolean\(lockMessage\)\)/)
  assert.match(component, /View Specification · Read only/)
  assert.match(component, /disabled=\{readOnlyMode\}/)
  assert.match(component, /Product Specification Report/)
  assert.match(component, /!readOnlyMode && <button type="submit"/)
  assert.match(styles, /\.spec-edit-button\.is-locked/)
  assert.match(styles, /\.product-spec-readonly-fields:disabled/)
})

test('product dimensions are explicitly identified as Outer Dimensions', async () => {
  const component = await readFile('src/features/product-specifications/ProductSpecifications.tsx', 'utf8')

  assert.match(component, /Length - OD \(mm\)/)
  assert.match(component, /Width - OD \(mm\)/)
  assert.match(component, /Height - OD \(mm\)/)
  assert.match(component, /Length \(OD\)/)
})
