import { useEffect,useState } from 'react'
import { Download,RotateCcw } from 'lucide-react'
import { formatIstDate } from '../../utils/dateTimeFormatting'
import { loadFinishedGoodsStock,type FinishedGoodsResult } from './finishedGoodsStockService'
import './finished-goods-stock.css'

const initial=()=>({from_date:'',to_date:'',customer_id:'',sales_order:'',job_card:'',item:''})
const quantity=(value:number)=>new Intl.NumberFormat('en-IN',{maximumFractionDigits:3}).format(value)
const escapeXml=(value:unknown)=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')
const displayDate=(value:string)=>value?formatIstDate(value):'—'

export default function FinishedGoodsStock({username}:{username:string}){
  const[filters,setFilters]=useState(initial),[result,setResult]=useState<FinishedGoodsResult>({rows:[],customers:[]})
  const[busy,setBusy]=useState(false),[error,setError]=useState('')
  const load=async(next=filters)=>{setBusy(true);setError('');try{setResult(await loadFinishedGoodsStock(next))}catch(reason){setError(reason instanceof Error?reason.message:'Unable to load Finished Goods Stock.')}finally{setBusy(false)}}
  useEffect(()=>{void load(initial())},[])
  const change=(key:keyof ReturnType<typeof initial>,value:string)=>setFilters(current=>({...current,[key]:value}))
  const reset=()=>{const next=initial();setFilters(next);void load(next)}
  const exportExcel=()=>{
    const headers=['SO','Customer','Item & Description','Job Card No.','Manufactured Date','Manufactured Qty']
    const rows=result.rows.map(row=>[row.sales_order_number,row.customer_name,[row.polar_canvas_item_code,row.item_name,row.item_description].filter(Boolean).join(' - '),row.job_number,displayDate(row.manufactured_date),`${quantity(row.manufactured_quantity)} ${row.uom||'Nos'}`])
    const metadata=`<Row><Cell><Data ss:Type="String">Finished Goods Stock (FG Stock Report)</Data></Cell></Row><Row><Cell><Data ss:Type="String">Generated By</Data></Cell><Cell><Data ss:Type="String">${escapeXml(username)}</Data></Cell></Row>`
    const xml=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="FG Stock"><Table>${metadata}<Row>${headers.map(value=>`<Cell><Data ss:Type="String">${escapeXml(value)}</Data></Cell>`).join('')}</Row>${rows.map(row=>`<Row>${row.map(value=>`<Cell><Data ss:Type="String">${escapeXml(value)}</Data></Cell>`).join('')}</Row>`).join('')}</Table></Worksheet></Workbook>`
    const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([xml],{type:'application/vnd.ms-excel'}));link.download='Finished-Goods-Stock.xls';link.click();URL.revokeObjectURL(link.href)
  }
  return <div className="fg-stock-page">
    {error&&<p className="fg-stock-message" role="alert">{error}</p>}
    <section className="fg-stock-filters">
      <label><span>From Date</span><input type="date" value={filters.from_date} onChange={event=>change('from_date',event.target.value)}/></label>
      <label><span>To Date</span><input type="date" value={filters.to_date} onChange={event=>change('to_date',event.target.value)}/></label>
      <label><span>Customer</span><select value={filters.customer_id} onChange={event=>change('customer_id',event.target.value)}><option value="">All Customers</option>{result.customers.map(customer=><option key={customer.customer_id} value={customer.customer_id}>{customer.customer_name}</option>)}</select></label>
      <label><span>Sale Order</span><input value={filters.sales_order} onChange={event=>change('sales_order',event.target.value)} placeholder="SO number"/></label>
      <label><span>Job Card No.</span><input value={filters.job_card} onChange={event=>change('job_card',event.target.value)} placeholder="Job Card"/></label>
      <label><span>Item</span><input value={filters.item} onChange={event=>change('item',event.target.value)} placeholder="Code, item or description"/></label>
      <div><button type="button" disabled={busy} onClick={()=>void load()}>Apply Filters</button><button type="button" className="secondary" disabled={busy} onClick={reset}><RotateCcw size={13}/> Reset</button><button type="button" className="export" disabled={busy||!result.rows.length} onClick={exportExcel}><Download size={13}/> Export Excel</button></div>
    </section>
    <section className="fg-stock-grid"><header><strong>Finished Goods Stock</strong><span>{result.rows.length} Job Cards</span></header><div><table><thead><tr>{['SO','Customer','Item & Description','Job Card No.','Manufactured Date','Manufactured Qty'].map(value=><th key={value}>{value}</th>)}</tr></thead><tbody>{result.rows.map(row=><tr key={row.job_card_id}><td>{row.sales_order_number}</td><td>{row.customer_name}</td><td className="item"><strong>{[row.polar_canvas_item_code,row.item_name].filter(Boolean).join(' · ')}</strong><small>{row.item_description||'—'}</small></td><td>{row.job_number}</td><td>{displayDate(row.manufactured_date)}</td><td className="qty">{quantity(row.manufactured_quantity)} <small>{row.uom||'Nos'}</small></td></tr>)}{!busy&&!result.rows.length&&<tr><td colSpan={6} className="empty">No Job Cards with Manufactured Quantity match the selected filters.</td></tr>}</tbody></table></div></section>
  </div>
}
